"""Ansible reproducer — emit a playbook that re-establishes a node's software state.

Installs the captured packages, enables the captured services, opens observed listener ports,
and templates captured config files. Pairs with a Terraform reproducer (which makes the box)
to fully recreate a system: infra + configuration.
"""
from __future__ import annotations

from ..models import Node, OSFamily
from . import Artifact, Reproducer


class AnsibleReproducer(Reproducer):
    target = "ansible"

    def reproduce(self, node: Node) -> list[Artifact]:
        inv = node.software
        pkg_mgr = self._package_module(node)

        tasks: list[str] = []

        packages = sorted({p.name for p in inv.packages if p.name})
        if packages:
            pkg_list = "\n".join(f"      - {p}" for p in packages)
            tasks.append(
                f"  - name: Install captured packages\n"
                f"    {pkg_mgr}:\n"
                f"      name:\n{pkg_list}\n"
                f"      state: present\n"
            )

        services = sorted({s.name for s in inv.services if s.name})
        if services:
            svc_list = "\n".join(f"      - {s}" for s in services)
            tasks.append(
                "  - name: Enable & start captured services\n"
                "    ansible.builtin.service:\n"
                "      name: \"{{ item }}\"\n"
                "      state: started\n"
                "      enabled: true\n"
                f"    loop:\n{svc_list}\n"
            )

        ports = sorted({p.port for p in inv.listeners})
        if ports:
            port_list = "\n".join(f"      - {p}" for p in ports)
            tasks.append(
                "  - name: Open observed listener ports (firewalld)\n"
                "    ansible.posix.firewalld:\n"
                "      port: \"{{ item }}/tcp\"\n"
                "      permanent: true\n"
                "      immediate: true\n"
                "      state: enabled\n"
                f"    loop:\n{port_list}\n"
                "    ignore_errors: true   # firewalld may not be present\n"
            )

        config_with_content = [c for c in inv.config_files if c.content]
        for c in config_with_content:
            tasks.append(
                f"  - name: Restore config {c.path}\n"
                "    ansible.builtin.copy:\n"
                f"      dest: {c.path}\n"
                f"      owner: {c.owner or 'root'}\n"
                f"      group: {c.group or 'root'}\n"
                f"      mode: '{c.mode or '0644'}'\n"
                f"      content: \"{{{{ lookup('file', 'files/{_safe(c.path)}') }}}}\"\n"
            )

        if not tasks:
            tasks.append(
                "  - name: No software captured — run deep inspection first\n"
                "    ansible.builtin.debug:\n"
                "      msg: \"Run 'fleetview inspect' to populate software inventory.\"\n"
            )

        playbook = (
            f"# Generated by FleetView — reconfigure a host to match \"{node.name}\"\n"
            f"# Source: {node.source.provider.value} ({node.source.native_id}); "
            f"OS: {node.os.distro or node.os.family.value}\n"
            "---\n"
            f"- name: Recreate {node.name}\n"
            "  hosts: target\n"
            "  become: true\n"
            "  tasks:\n"
            + "\n".join(tasks)
        )

        inventory = "[target]\n" + (node.primary_ip or "TARGET_HOST") + "\n"
        artifacts = [
            Artifact("site.yml", playbook, "ansible"),
            Artifact("inventory.ini", inventory, "ansible"),
        ]
        for c in config_with_content:
            artifacts.append(Artifact(f"files/{_safe(c.path)}", c.content or "", "ansible"))
        return artifacts

    @staticmethod
    def _package_module(node: Node) -> str:
        # Choose a package module from OS family / observed managers.
        managers = {p.manager for p in node.software.packages if p.manager}
        if "apt" in managers or node.os.family == OSFamily.LINUX and (node.os.distro or "").lower().startswith(("ubuntu", "debian")):
            return "ansible.builtin.apt"
        if "yum" in managers or "dnf" in managers:
            return "ansible.builtin.dnf"
        return "ansible.builtin.package"


def _safe(path: str) -> str:
    return path.strip("/").replace("/", "_") or "file"
