"""Terraform reproducers — emit HCL that recreates a Node on AWS or vSphere.

Written directly against the typed Node model (clearer than templating from raw provider
dicts). Output is best-effort scaffolding a human reviews before `terraform apply` — it pins
the shape, disks, networking, and tags we captured.
"""
from __future__ import annotations

from ..analyze.pricing import estimate
from ..models import Node, ProviderKind
from . import Artifact, Reproducer


def _hcl_tags(tags: dict[str, str]) -> str:
    if not tags:
        return "{}"
    inner = "\n".join(f'    "{k}" = "{v}"' for k, v in tags.items())
    return "{\n" + inner + "\n  }"


def _provider_block(provider: str, body: str) -> str:
    return f'terraform {{\n  required_providers {{}}\n}}\n\nprovider "{provider}" {{\n{body}\n}}\n'


class TerraformAWSReproducer(Reproducer):
    """Recreate a node as an AWS EC2 instance."""

    target = "terraform-aws"

    def reproduce(self, node: Node) -> list[Artifact]:
        vcpus = node.compute.vcpus or 2
        mem = node.compute.memory_mb or 4096
        root_gb = int(max((d.size_gb or 0) for d in node.disks) if node.disks else 20)
        inst_type = node.compute.instance_type or estimate(ProviderKind.AWS, vcpus, mem)[0] or "t3.medium"
        ports = sorted({p.port for p in node.software.listeners}) or [22]
        tags = {"Name": node.name, **node.tags}

        main = f'''# Generated by FleetView — recreate "{node.name}" on AWS
# Source: {node.source.provider.value} ({node.source.native_id})
# Review before applying. AMI is a placeholder — pick one matching {node.os.distro or node.os.family.value}.

variable "ami_id"   {{ type = string, description = "AMI matching the source OS" }}
variable "key_name" {{ type = string, default = "" }}
variable "subnet_id" {{ type = string, default = "" }}

resource "aws_instance" "{_san(node.name)}" {{
  ami           = var.ami_id
  instance_type = "{inst_type}"   # {vcpus} vCPU / {mem} MB
  key_name      = var.key_name != "" ? var.key_name : null
  subnet_id     = var.subnet_id != "" ? var.subnet_id : null

  root_block_device {{
    volume_size = {root_gb}
    volume_type = "gp3"
  }}

  vpc_security_group_ids = [aws_security_group.{_san(node.name)}_sg.id]

  tags = {_hcl_tags(tags)}
}}

resource "aws_security_group" "{_san(node.name)}_sg" {{
  name        = "{_san(node.name)}-sg"
  description = "Ports observed on {node.name}"
{_aws_ingress(ports)}
  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}
}}
'''
        extra_disks = "".join(_aws_ebs(node, i, d) for i, d in enumerate(node.disks[1:], start=1))
        if extra_disks:
            main += "\n# Additional data disks\n" + extra_disks

        outputs = f'output "instance_id" {{ value = aws_instance.{_san(node.name)}.id }}\n'
        provider = _provider_block("aws", '  region = var.region')
        variables = 'variable "region" { type = string, default = "us-east-1" }\n'
        return [
            Artifact("main.tf", main, "terraform"),
            Artifact("provider.tf", provider, "terraform"),
            Artifact("variables.tf", variables, "terraform"),
            Artifact("outputs.tf", outputs, "terraform"),
        ]


class TerraformVSphereReproducer(Reproducer):
    """Recreate a node as a vSphere VM (clone-from-template scaffold)."""

    target = "terraform-vsphere"

    def reproduce(self, node: Node) -> list[Artifact]:
        vcpus = node.compute.vcpus or 2
        mem = node.compute.memory_mb or 4096
        disks = node.disks or []
        disk_blocks = "\n".join(
            f'''  disk {{
    label            = "disk{i}"
    size             = {int(d.size_gb or 20)}
    thin_provisioned = {str((d.provisioning or "thin") == "thin").lower()}
    unit_number      = {i}
  }}'''
            for i, d in enumerate(disks)
        ) or '''  disk {
    label = "disk0"
    size  = 20
  }'''

        main = f'''# Generated by FleetView — recreate "{node.name}" on vSphere
# Source: {node.source.provider.value} ({node.source.native_id})

data "vsphere_datacenter" "dc"   {{ name = var.datacenter }}
data "vsphere_datastore" "ds"    {{ name = var.datastore,  datacenter_id = data.vsphere_datacenter.dc.id }}
data "vsphere_resource_pool" "rp" {{ name = var.resource_pool, datacenter_id = data.vsphere_datacenter.dc.id }}
data "vsphere_network" "net"     {{ name = var.network, datacenter_id = data.vsphere_datacenter.dc.id }}
data "vsphere_virtual_machine" "template" {{ name = var.template, datacenter_id = data.vsphere_datacenter.dc.id }}

resource "vsphere_virtual_machine" "{_san(node.name)}" {{
  name             = "{node.name}"
  resource_pool_id = data.vsphere_resource_pool.rp.id
  datastore_id     = data.vsphere_datastore.ds.id
  num_cpus         = {vcpus}
  memory           = {mem}
  guest_id         = data.vsphere_virtual_machine.template.guest_id

  network_interface {{
    network_id = data.vsphere_network.net.id
  }}

{disk_blocks}

  clone {{
    template_uuid = data.vsphere_virtual_machine.template.id
  }}
}}
'''
        variables = "\n".join(
            f'variable "{v}" {{ type = string{d} }}'
            for v, d in [
                ("datacenter", f', default = "{node.placement.datacenter or ""}"'),
                ("datastore", ""),
                ("resource_pool", ""),
                ("network", f', default = "{(node.nics[0].network if node.nics else "") or ""}"'),
                ("template", ', description = "Source VM template to clone"'),
            ]
        ) + "\n"
        provider = _provider_block(
            "vsphere",
            '  user                 = var.vsphere_user\n'
            '  password             = var.vsphere_password\n'
            '  vsphere_server       = var.vsphere_server\n'
            '  allow_unverified_ssl = true',
        )
        provider_vars = (
            'variable "vsphere_user" { type = string }\n'
            'variable "vsphere_password" { type = string, sensitive = true }\n'
            'variable "vsphere_server" { type = string }\n'
        )
        return [
            Artifact("main.tf", main, "terraform"),
            Artifact("provider.tf", provider, "terraform"),
            Artifact("variables.tf", variables + provider_vars, "terraform"),
        ]


# ----------------------------------------------------------------- helpers


def _san(name: str) -> str:
    """Sanitize a name into a valid Terraform resource identifier."""
    out = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return out if out[:1].isalpha() or out[:1] == "_" else f"vm_{out}"


def _aws_ingress(ports: list[int]) -> str:
    blocks = []
    for p in ports:
        blocks.append(
            f'''  ingress {{
    from_port   = {p}
    to_port     = {p}
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}'''
        )
    return "\n".join(blocks) + "\n"


def _aws_ebs(node: Node, idx: int, disk) -> str:
    return f'''resource "aws_ebs_volume" "{_san(node.name)}_data{idx}" {{
  availability_zone = aws_instance.{_san(node.name)}.availability_zone
  size              = {int(disk.size_gb or 10)}
  type              = "gp3"
}}

resource "aws_volume_attachment" "{_san(node.name)}_data{idx}_att" {{
  device_name = "/dev/sd{chr(ord('f') + idx - 1)}"
  volume_id   = aws_ebs_volume.{_san(node.name)}_data{idx}.id
  instance_id = aws_instance.{_san(node.name)}.id
}}

'''
